wandb_version: 1

project:
  desc: null
  value: CORL
group:
  desc: null
  value: DT-D4RL
name:
  desc: null
  value: DT-halfcheetah-medium-v2-484d2f39
embedding_dim:
  desc: null
  value: 128
num_layers:
  desc: null
  value: 3
num_heads:
  desc: null
  value: 1
seq_len:
  desc: null
  value: 20
episode_len:
  desc: null
  value: 1000
attention_dropout:
  desc: null
  value: 0.1
residual_dropout:
  desc: null
  value: 0.1
embedding_dropout:
  desc: null
  value: 0.1
max_action:
  desc: null
  value: 1.0
env_name:
  desc: null
  value: halfcheetah-medium-v2
learning_rate:
  desc: null
  value: 0.0001
betas:
  desc: null
  value:
  - 0.9
  - 0.999
weight_decay:
  desc: null
  value: 0.0001
clip_grad:
  desc: null
  value: 0.25
batch_size:
  desc: null
  value: 64
update_steps:
  desc: null
  value: 100000
warmup_steps:
  desc: null
  value: 10000
reward_scale:
  desc: null
  value: 0.001
num_workers:
  desc: null
  value: 4
target_returns:
  desc: null
  value:
  - 12000.0
  - 6000.0
eval_episodes:
  desc: null
  value: 100
eval_every:
  desc: null
  value: 10000
checkpoints_path:
  desc: null
  value: null
deterministic_torch:
  desc: null
  value: false
train_seed:
  desc: null
  value: 10
eval_seed:
  desc: null
  value: 42
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688053555.100246
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.10.9
      5: 0.15.3
      8:
      - 5
      10:
      - 3
